version: '3.8'

services:
  backend:
    build:
      # The backend has its own folder, so the context is correct
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: hummingbird-backend-dev
    ports:
      - "3001:3001"
    environment:
      - VITE_API_URL=http://backend:3001
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm start
    restart: unless-stopped
    networks:
      - hummingbird-network

  frontend:
    build:
      # Change the context to '.' to point to the current directory (the root)
      context: .
      dockerfile: Dockerfile.dev
    container_name: hummingbird-frontend-dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:3001
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    restart: unless-stopped
    networks:
      - hummingbird-network

networks:
  hummingbird-network:
    driver: bridge